### ISSUE TITLE
New icon request: "IOTA" - Internet of Things (IoT)

### ISSUE THREAD

**Issue by romfis85** [tomwilusz/lord-icon-icons#1]
Hello,

my Name is Roman F. and a customer from you. I read totay your eMail and by random found the ICON request Link. And spontaneous becom a idea for Animated IOTA Logo for the IOTA Foundation in Germany / Berlin - Note: I am not from the foundation. Than i look in your Icon Library if have a finance category and foundit something with BTC and ETH. :)
I think this is a good reason for more icons in your category. I hope give you to inspire for this Icon. And it would be surprise for the foundation. :)

I hope u understand me, my english not so the best, i am from austria.

**What is the meaning of the icon?**
Shortly describe what should the icon present. 

IOTA is an open-source distributed ledger and cryptocurrency designed for the Internet of things (IoT). It uses a directed acyclic graph to store transactions on its ledger, motivated by a potentially higher scalability over blockchain based distributed ledgers. IOTA does not use miners to validate transactions, instead, users that issue a new transaction must approve two previous transactions and perform a small amount of proof of work. Transactions can therefore be issued without fees, facilitating microtransactions. If you whant more information check: www.iota.org

**Reference image**
Insert the link with the reference image here.

Here a link: https://www.iota.org/connect/brand

Many Greetings.

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1121-iota-internet-of-things-outline
