### ISSUE TITLE
Workout Icon

### ISSUE THREAD

**Issue by Charliewxjj** [tomwilusz/lord-icon-icons#111]
**What is the meaning of the icon?**
Shortly describe what should the icon present. 

**Reference image**
Insert the link with the reference image here.
https://www.google.com/search?q=Icon+de+treino&sxsrf=AOaemvKrW0hnWGjRAbNE6gIv57RDQ1kilQ:1642861120517&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjPsoPMxsX1AhUulJUCHcF6DpQQ_AUoAXoECAEQAw&biw=1236&bih=597&dpr=1.1#imgrc=gAl_dzKEDmDCmM

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by Charliewxjj** [comment]
Hi! I would like to have a training icon, it would be very useful, thank you good work <3

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/wired/outline/1774-strenght
