### ISSUE TITLE
information icon

### ISSUE THREAD

**Issue by japomani** [tomwilusz/lord-icon-icons#116]
**What is the meaning of the icon?**
mouse over to see information in UI

**Reference image**
https://www.google.com/search?q=information&tbm=isch&tbs=rimg:CcEI6QDCc5XHYcR-D_1EJXijXsgIMCgIIABAAOgQIARAA&rlz=1C1GCEU_enUS858US858&hl=en&sa=X&ved=0CAIQrnZqFwoTCLDeh7TB-vUCFQAAAAAdAAAAABAH&biw=1519&bih=761

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ x] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/system/outline/28-info
