### ISSUE TITLE
New icon request - bunch of flowers?

### ISSUE THREAD

**Issue by brendanknights** [tomwilusz/lord-icon-icons#13]
**What is the meaning of the icon?**
A bunch of flowers (we're florists!)
Bouquet gift, Wedding Bouquet, Table Flowers etc

**Reference image**
https://www.pinterest.com.au/pin/746119863248805765/
or
https://www.hiclipart.com/free-transparent-background-png-clipart-jdcep

**Icon request checklist**
- [ x  ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ x  ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

Maybe the animation could be a swaying bunch of flowers? Or 'nodding' flower heads?

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1621-flower-bouquet-outline
