### ISSUE TITLE
New icon request - FEMALE SIGN/SYMBOL FOR WOMEN'S DAY

### ISSUE THREAD

**Issue by SebastianCodeAI** [tomwilusz/lord-icon-icons#14]
**What is the meaning of the icon?**
Symbolises women and would be a great new icon for women's day and female empowerment

**Reference image**
https://en.wikipedia.org/wiki/File:Female_symbol.svg

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `add` / `delete`)
- [X] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
Icon added to the library (Icon no: #840)
