### ISSUE TITLE
Scooter

### ISSUE THREAD

**Issue by cf72** [tomwilusz/lord-icon-icons#16]
**What is the meaning of the icon?**
Surprised that there isn't any icon about the new way of transport: e-Scooter and Hoverboards

**Reference image**
Scooter:
https://www.flaticon.com/free-icon/scooter_502674

Hoverboard:
https://www.flaticon.com/free-icon/hoverboard_4109865?term=hoverboard&page=1&position=9&page=1&position=9&related_id=4109865&origin=style

**Icon request checklist**
- [X ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [X ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/941-scooter-outline

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/794-segway-outline
