### ISSUE TITLE
New icon request - Thumb-Down

### ISSUE THREAD

**Issue by TaoTek** [tomwilusz/lord-icon-icons#2]
**What is the meaning of the icon?**
There is a Thumb-Up Icon, I was hoping for the opposite, a Thumb-Down Icon. Would love to have the opposite (so that there is a matching pair) for the one that already exists so that I can use both on my web site. I have the full pack and was hoping that I might be able to load it into the editor and just invert it but that doesn't seem to be an option. 

**Reference image**
Insert the link with the reference image here. https://www.123rf.com/photo_42621317_stock-vector-thumbs-down-dislike-line-art-icon-for-apps.html 
But just exactly like the Thumb-Up, just inverted.

**Icon request checklist**
- [Single that would complete a matching pair] This is a single icon or matched pair (Ex: `add` / `delete`)
- [X ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1122-thumb-down-outline
