### ISSUE TITLE
Shoes

### ISSUE THREAD

**Issue by FernandoTWE** [tomwilusz/lord-icon-icons#20]
**What is the meaning of the icon?**
A shoe or heels. Very useful for ecommerce with category shoes or to symbolize walking or following steps. It could be used for several functionalities. 

**Reference image**
https://www.iconfinder.com/icons/4489391/school_shoe_shoes_sneakers_icon

**Icon request checklist**
- [add] This is a single icon or matched pair 
- [x] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1692-running-shoe-outline
More versions of shoes are coming soon.
