### ISSUE TITLE
New icon request (2 ideas)

### ISSUE THREAD

**Issue by JLModels** [tomwilusz/lord-icon-icons#22]
**What is the meaning of the icon?**
Shortly describe what should the icon present. 

First icon should present "park & recreations" for example a tree + a bench or a bin next to it, something representing a park and "natural" feeling, yet still being inside a city.

Second icon should be a parking spot (example a P) or a parked car with "P" sign next to it. (additionally, expand it to parking garage as well)

**Reference image**
Insert the link with the reference image here.
first icon:
![image](https://user-images.githubusercontent.com/64324430/111759108-8ce51b00-889d-11eb-8e73-77b79126d416.png)

second icon:
![image](https://user-images.githubusercontent.com/64324430/111759156-9a9aa080-889d-11eb-915d-dcc2497f103c.png)
or 
![image](https://user-images.githubusercontent.com/64324430/111759180-9ec6be00-889d-11eb-8105-064b9b0f7deb.png)
garage icon:
![image](https://user-images.githubusercontent.com/64324430/111759288-b605ab80-889d-11eb-940c-b8567940614f.png)

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [x ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
This is what we have recently added. More specific icons listed above will be added soon as well.
https://lordicon.com/icons/867-parking-meter-outline

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/445-forest-outline
https://lordicon.com/icons/853-car-in-garage-outline
