### ISSUE TITLE
New icon request: Animated mountain with snow

### ISSUE THREAD

**Issue by flawlesswebsitedesign** [tomwilusz/lord-icon-icons#23]
**What is the meaning of the icon?**
A mountain with snow on top.

**Reference image**
Here's an example: https://icons8.com/icon/25055/mountain

**Icon request checklist**
- [check ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [check ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1680-mountains-outline
