### ISSUE TITLE
New new social media icons request 

### ISSUE THREAD

**Issue by Sajeevan19** [tomwilusz/lord-icon-icons#24]
**What is the meaning of the icon?**
social media icons like Facebook, Instagram, twitter...etc.

**Reference image**
https://www.google.com/url?sa=i&url=https%3A%2F%2Fbandzoogle.com%2Fblog%2Fnew-updated-options-for-social-media-icons&psig=AOvVaw1p-sX1w17ogRjQnKxhZJ5A&ust=1617025451766000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCODb2q-P0-8CFQAAAAAdAAAAABAD

**Icon request checklist**
Facebook
Instagram
whatapp
twitter
github
..
..

**Comment by jasonrmh** [comment]
Also
- YouTube
- Google My Business

**Comment by tomwilusz** [comment]
Unfortunately, we can not legally share animated versions of brand logos.
