### ISSUE TITLE
New icon request 

### ISSUE THREAD

**Issue by JacobACrocker** [tomwilusz/lord-icon-icons#32]
**What is the meaning of the icon?**
A pencil

**Reference image**
https://www.creativefabrica.com/wp-content/uploads/2018/12/Pencil-icon-vector-by-Hoeda80-580x386.jpg

**Icon request checklist**
- [ ] This is a single icon
- [ ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/35-edit-outline
