### ISSUE TITLE
New icon request 

### ISSUE THREAD

**Issue by nabiebaby** [tomwilusz/lord-icon-icons#34]
**What is the meaning of the icon?**
With summer coming soon, I would love to see an icon of a flower, such as sunflower, rose, or tulip.

**Reference image**
https://static.wixstatic.com/media/e6591e_3a5449fe774a4993a1166b1d33e233f7~mv2_d_1880_1253_s_2.jpg/v1/fill/w_1000,h_666,al_c,q_90,usm_0.66_1.00_0.01/e6591e_3a5449fe774a4993a1166b1d33e233f7~mv2_d_1880_1253_s_2.jpg

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ x] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1621-flower-bouquet-outline
