### ISSUE TITLE
New icon request: augmented reality

### ISSUE THREAD

**Issue by friedrith** [tomwilusz/lord-icon-icons#36]
**What is the meaning of the icon?**

A new icon related to augmented reality would be nice. It could be AR in smartphone or AR in a headset.

**Reference image**

An example in another existing libraries is there: https://www.flaticon.com/premium-icon/augmented-reality_3772289

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `add` / `delete`)
- [x] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1458-agumented-reality-outline
