### ISSUE TITLE
New icon request - Social media links

### ISSUE THREAD

**Issue by unboogyman** [tomwilusz/lord-icon-icons#37]
**What is the meaning of the icon?**
Hi, just wondering why you don't have social media links as icons? I would love an animated instagram or facebook icon from you guys 

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [x ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
Unfortunately, we can not legally share animated versions of brand logos.
