### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by muhammawq** [tomwilusz/lord-icon-icons#39]
**What is the meaning of the icon?**
Shortly describe what should the icon present. 

**Reference image**
Insert the link with the reference image here.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
Can't find enough information about new icon request.

The verification-type icons are already in the library: 
https://lordicon.com/icons/14-doc-ok-outline
https://lordicon.com/icons/24-approved-checked-outline
