### ISSUE TITLE
Sheet Document Icon

### ISSUE THREAD

**Issue by Bannerman** [tomwilusz/lord-icon-icons#4]
**What is the meaning of the icon?**
I love the animated document icons. I'd love to see a "Sheet" version to represent Google Sheets files. 

**Reference image**
81-ppt-document-outline

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `add` / `delete`)
- [x] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1124-google-sheet-document-icon-outline
