### ISSUE TITLE
New icon set request - E-learning/Teaching

### ISSUE THREAD

**Issue by Sal1C** [tomwilusz/lord-icon-icons#44]
**What is the meaning of the icon?**
The icon/icons should allow Lordicon users who sell online courses to properly describe the nature of their business through icons. To that end, the following icons should be available:

See reference imanges below

**Reference image**

1. https://www.iconfinder.com/icons/3986952/competition_question_quiz_icon

**Icon request checklist**
- [ X ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ X ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
Thank you for sharing, unfortunately, this icon is too complex for our style.
