### ISSUE TITLE
New icon request 

### ISSUE THREAD

**Issue by KBigMac** [tomwilusz/lord-icon-icons#49]
**What is the meaning of the icon?**
Lightening Bolt

**Reference image**
Insert the link with the reference image here.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `add` / `delete`)
- [x] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/451-electric-power-outline
