### ISSUE TITLE
New icon request 

### ISSUE THREAD

**Issue by basmaade** [tomwilusz/lord-icon-icons#51]
**What is the meaning of the icon?**
Shortly describe what should the icon present. 
ui and ux icon

**Reference image**
Insert the link with the reference image here.
![1447290](https://user-images.githubusercontent.com/88151355/127511876-d6c718f5-0a2f-4da3-b3fb-441ffd8f495f.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `add` / `delete`)
- [x] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1329-responsive-outline or similar
