### ISSUE TITLE
Classrooms New icon request 

### ISSUE THREAD

**Issue by hussien7** [tomwilusz/lord-icon-icons#52]
**What is the meaning of the icon?**
Shortly describe what should the icon present. 

**Reference image**
Insert the link with the reference image here.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/116-blackboard-school-morph-outline
