### ISSUE TITLE
New icon request 

### ISSUE THREAD

**Issue by ViandVending** [tomwilusz/lord-icon-icons#57]
**What is the meaning of the icon?**
Shortly describe what should the icon present. 
vending machines, chips, soda candy, simple and cute

**Reference image**
Insert the link with the reference image here.

**Icon request checklist**
- [add ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ yes] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1119-candy-machine-lottery-outline
https://lordicon.com/icons/605-chips-snacks-outline
https://lordicon.com/icons/620-candy-outline
https://lordicon.com/icons/607-lolipop-candy-outline
