### ISSUE TITLE
New icon request 

### ISSUE THREAD

**Issue by itshumi** [tomwilusz/lord-icon-icons#58]
**What is the meaning of the icon?**
WhatsApp icon

**Reference image**
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.flaticon.es%2Ficono-gratis%2Fwhatsapp_174879&psig=AOvVaw11J2bhGYRTQGlu_NlMSrNB&ust=1628507992415000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCIC0qZWnofICFQAAAAAdAAAAABAD

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
Unfortunately, we can not legally share animated versions of brand logos.
