### ISSUE TITLE
New icon request 

### ISSUE THREAD

**Issue by deequiambao** [tomwilusz/lord-icon-icons#59]
Hi can you guys add store icons like Restaurant, Grocery Store, Bake shop, Pharmacy etc.? 

This will be a great addition. Thanks

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1248-pharmacy
https://lordicon.com/icons/1013-barbershop-outline
https://lordicon.com/icons/481-shop-outline

Others are coming soon.
