### ISSUE TITLE
New icon request 

### ISSUE THREAD

**Issue by Nicholasonebron** [tomwilusz/lord-icon-icons#66]
**What is the meaning of the icon?**
Icon of Google Ads

**Reference image**
https://freeicons.io/social-media/calendar-google-ads-icon-6218

**Icon request checklist**
- [ x ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ x ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
Unfortunately, we can not legally share animated versions of brand logos.
