### ISSUE TITLE
New icon request 

### ISSUE THREAD

**Issue by naziko13** [tomwilusz/lord-icon-icons#67]
**What is the meaning of the icon?**
Shortly describe what should the icon present. 
insuarance

**Reference image**
Insert the link with the reference image here.
https://www.google.com/search?q=insurance+icon&source=lmns&bih=923&biw=1414&hl=en&sa=X&ved=2ahUKEwjYqau6pb3yAhWl8rsIHTvbC7AQ_AUoAHoECAEQAA
**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/1267-medical-insurance
