### ISSUE TITLE
New icon request Barcode or Barcode Scanner

### ISSUE THREAD

**Issue by rafiksom** [tomwilusz/lord-icon-icons#7]
**What is the meaning of the icon?**
Icon's for barcode scanning functionality, maybe on mobile phones.

**Reference image**
https://cdn4.iconfinder.com/data/icons/add-1/60/barcode-512.png

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [X] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
Here you are: https://lordicon.com/icons/1001-shop-scanner-outline
Barcode alone will be added later
