### ISSUE TITLE
New icon request 

### ISSUE THREAD

**Issue by zmkinviz** [tomwilusz/lord-icon-icons#70]
**What is the meaning of the icon?**
Motorcycle / Vespa / Scooter 
I want to use it for Food delivery app. You only have electric scooter, bike , electric bike

**Reference image**
https://www.iconpacks.net/free-icon/scooter-1050.html

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/843-bike-outline

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/495-scooter-outline
