### ISSUE TITLE
New icon request 

### ISSUE THREAD

**Issue by pierpaolo707** [tomwilusz/lord-icon-icons#78]
**What is the meaning of the icon?**
i'll need an icon that will redirect the user to our social pages

**Reference image**
i don't have a link but if is it possible i would like to have an animation with the facebook and instagram's logos
**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `add` / `delete`)
- [ ] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
We are not allowed to animate social brands logos unless they agree to.
