### ISSUE TITLE
New icon request - meditation

### ISSUE THREAD

**Issue by revtech12** [tomwilusz/lord-icon-icons#88]
**What is the meaning of the icon?**
someone sitting in meditation posture (please make features of person of color included) 

**Reference image**
https://images.app.goo.gl/mNSKRekmgVWXuE7S7

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `add` / `delete`)
- [x] I have [searched for existing icons](http://lordicon.com/icons) and to the best of my knowledge this is not a duplicate

**Comment by tomwilusz** [comment]
https://lordicon.com/icons/628-yoga-female-outline
